#version 450



layout (binding = 0, rgba8) uniform writeonly image2D outputImage;


// work group max size on this computer is 1024 
layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main(){

    ivec2 xy_int = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outputImage);
    vec2 xy_float = vec2(gl_GlobalInvocationID.x / float(size.x), gl_GlobalInvocationID.y / float(size.y));
    
    imageStore(outputImage, xy_int, vec4(xy_float.xy, 0.0f , 1.0f));
}